In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [30]:
def to_multiple_data_set(data_set, k):
    result = []
    for i in range(k-1):
        tmp = data_set[0:i+1]
        for j in range(k-i-1):
            tmp = np.insert(tmp, 0, 0, 0)
        result.append(tmp)
    for i in range(len(data_set)-k+1):
        tmp = data_set[i:i+k]
        result.append(tmp)
    return np.array(result)

In [31]:
b = to_multiple_data_set(a, 3)

In [32]:
print b

[[0 0 1]
 [0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
